### ISSUE TITLE
[LiveCryptoPanel_upbitAPI] JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by KnightChaser** [x3onkait/LiveCLICryptoPanel#1]
Unexpected error occurred while running (update cycle 647)
647회째 업데이트 하던 중 갑자기 예상치 못한 오류 발생. 

JSON 처리 관련으로 보이는데, 자세한건 아직 모름.

Error traceback
```
Traceback (most recent call last):
  File "LiveCryptoPanel_upbitAPI.py", line 164, in <module>
  File "LiveCryptoPanel_upbitAPI.py", line 131, in runProgram
  File "LiveCryptoPanel_upbitAPI.py", line 57, in cryptoDataProcessing
  File "LiveCryptoPanel_upbitAPI.py", line 49, in gatherInformation
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[10572] Failed to execute script 'LiveCryptoPanel_upbitAPI' due to unhandled exception!
```

**Comment by KnightChaser** [comment]
[웹에서 찾은 동일 오류 해결책(KR)](https://frhyme.github.io/python-libs/python_JSONDecodeError/)

Found Resolution. Pending to fix the bug...
해결방법 찾음. 버그 고치기 위해 대기중...

(일단 자료 확보해놨으니 나중에 코드 검토 후, 고치고 performance test를 다시 할 예정)

**Comment by KnightChaser** [comment]
Another case (update cycle 2653)
2653회째 업데이트 중에 동일 오류 또 발생

수정이 시급하다...

```
Traceback (most recent call last):
  File "LiveCryptoPanel_upbitAPI.py", line 164, in <module>
  File "LiveCryptoPanel_upbitAPI.py", line 131, in runProgram
  File "LiveCryptoPanel_upbitAPI.py", line 57, in cryptoDataProcessing
  File "LiveCryptoPanel_upbitAPI.py", line 49, in gatherInformation
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[19940] Failed to execute script 'LiveCryptoPanel_upbitAPI' due to unhandled exception!
```

**Comment by KnightChaser** [comment]
Added try-catch sentence to retain fault tolerance.
오류 감내성을 포함하기 위해 try-catch 문 사용

```py
    # gatherInformation()
    try:
        cryptoDataBundle = json.loads(responseCryptoAPI.text)
        return cryptoDataBundle
    except:
        return "JSONDecodeErrorAtGatheringInformation"
```

There will be no big performance gap due to error because it will retry the process in 2 seconds. 
이런 오류 발생시 2초 내로 데이터를 다시 받아오게 되므로 큰 성능차이는 없을것 같다.
```py
 #runProgram()
 elif runtimeResult == "JSONDecodeErrorAtGatheringInformation":
            exceptionCount += 1
            print("JSON Decode exception at data processing. Retry in 2 seconds. | JSON 형태의 데이터를 디코딩하는 중 예외상황발생. 2초 내 재시도합니다.")
```

**Comment by KnightChaser** [comment]
#4 

Accomplished!
해결 완료!
