### ISSUE TITLE
[LiveCryptoPanel_upbitAPI] Add graphing feature as termigraph package

### ISSUE THREAD

**Issue by KnightChaser** [x3onkait/LiveCLICryptoPanel#15]
Any part of the program is good, so it would be good to add graph-related functions to improve visual and functional.
프로그램의 어느 부분이라도 좋으니 시각 및 기능적인 개선을 위해 그래프 관련 기능을 넣으면 좋을 것 같다.

It may be good to use Stack-graph to compare the trading volume of the KRW market and BTC market, or to graph the market capitalization of cryptocurrency.
Stack-graph를 사용해 KRW 마켓과 BTC 마켓의 거래량을 비교하거나, 암호화폐의 시가총액을 그래프로 표시하는것도 좋을 것 같다. 

However, since there is a space limit to the terminal window where the program runs and shows its result, it is necessary to create a new program based on the existing program in order to professionally put the graph.
다만 프로그램이 돌아가는 터미널창의 지면적인 한계가 있기 때문에 그래프를 전문적으로 넣기 위해서는 기존에 만든 프로그램을 바탕으로 새로운 프로그램을 만들어야 할 것 같다.

**Comment by KnightChaser** [comment]
[Termgraph](https://github.com/mkaz/termgraph)
Teminal + graphing = Termgraph

I found a package that will help to resolve this issue.
이 이슈를 해결하는데 도움이 될만한 패키지를 찾았다.

[Another version of termgraph](https://github.com/sgeisler/termgraph)

It seems to be a good fit to draw a stock or cryptocurrency market graph. It is not a package, but it can be used to refer to source code.
주식이나 암호화폐 시황 그래프를 그리는데 적격인 것 같다. 패키지는 아닌데 소스코드 참고 정도는 할 수 있다.

**Comment by KnightChaser** [comment]
This package does not seem to allow negative values; for negative values, separate measures are needed, such as drawing a graph separately or not dealing with it at all.
이 패키지는 음수값을 허용하지 않는 것 같다. 음수값의 경우 따로 그래프를 그리던지 아예 다루지 않는 등 별도의 조치가 필요하다.

**Comment by KnightChaser** [comment]
원래는 CLI 명령어지만, Python의 "os" 패키지를 활용해 명령어를 실행시키는 쪽으로 프로그램 내에서 그래프를 그릴 수 있다.

example:

```
#data.dat 
2007,183.32,190.52
2008,231.23,5.0
2009,16.43,53.1
2010,50.21,7
2011,508.97,10.45
2012,212.05,20.2
2014,30.0,20.0
```

```python
import os

os.system("termgraph LiveCLICryptoPanel_upbitAPI\\termgraphData\data.dat --color {yellow,magenta} --stacked --title \"Stacked Data\"")
```

result
실행 결과

```
# Stacked Data

2007: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 373.84
2008: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▏ 236.23
2009: ▇▇▇▇▇▇ 69.53
2010: ▇▇▇▇▏ 57.21
2011: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 519.42
2012: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 232.25
2014: ▇▇▇ 50.00
```

**Comment by KnightChaser** [comment]
After two or three hours of research, there were many difficulties.
두세시간동안 연구해 본 결과, 많은 애로사항이 있었다.

It seems that we have to bring the file, and if you enter the file with a stdin, there are strange errors such as several pharmaceutical terms and not changing the number to a letter.
파일을 반드시 불러와야 하는 듯 하며, 파일 입력을 stdin으로 대신 하는 경우 여러 제약사항이 따르고, 숫자를 문자로 바꾸지 못한다는 등 이상한 에러가 뜬다.

In addition, there were cases where there was a file but it could not be found and the graph could not be drawn.
게다가, 파일이 있음에도 불구하고 이를 찾지 못해 그래프를 못 그리는 어이없는 경우도 있었다.

```
Traceback (most recent call last):
  File ".\LiveCryptoPanel_upbitAPI.py", line 296, in <module>
    runProgram()
  File ".\LiveCryptoPanel_upbitAPI.py", line 253, in runProgram
    FLAG, previousCryptoValueChange = cryptoDataPrinting(cryptoDataBundle, previousCryptoValueChange, cryptoShowQuantity, totalUPBITKRWMarketTradePrice24hr, totalUPBITBTCMarketTradePrice24hr, currentBTCprice)
  File ".\LiveCryptoPanel_upbitAPI.py", line 167, in cryptoDataPrinting
    termgraphDataMarketDominance = open("LiveCLICryptoPanel_upbitAPI/termgraphData/KRW_BTC_market_dominance.bat", 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'LiveCLICryptoPanel_upbitAPI/termgraphData/KRW_BTC_market_dominance.bat'
```

We should think about this graph display function a little more.
이 그래프 표시 기능은 조금 더 고민해야겠다.

**Comment by KnightChaser** [comment]
Once the data file has been updated, stored, and recalled every two seconds, it has been successful, but there is some delay in this process and there is a space constraint in the current program, so it is unlikely to add this function.
일단 데이터 파일을 계속 2초마다 갱신하고 저장하고 불러오는 식으로 구현은 성공했지만, 이 과정에서 지연이 좀 있고 현재 프로그램에는 공간 제약이 있어 이 기능을 추가하지 못할 것 같다.

File location
파일 위치
```
PS D:\CySECstudy\MyProgrammingProject\LiveCryptoPanel\LiveCLICryptoPanel_upbitAPI> ls -R


    디렉터리: D:\CySECstudy\MyProgrammingProject\LiveCryptoPanel\LiveCLICryptoPanel_upbitAPI


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----      2021-09-01   오후 4:13                termgraphData
d-----      2021-08-30   오전 1:14                __pycache__
-a----      2021-08-29  오후 10:22          26911 exampleUpbitCryptoMarketAPIresponse.json
-a----      2021-08-30   오후 7:22         242020 exampleUpbitTickerAPIresponse.json
-a----      2021-09-01   오후 4:08          16709 LiveCryptoPanel_upbitAPI.py
-a----      2021-08-30   오후 9:30         111695 upbit.ico
-a----      2021-08-30   오후 9:30          21562 upbit.png


    디렉터리: D:\CySECstudy\MyProgrammingProject\LiveCryptoPanel\LiveCLICryptoPanel_upbitAPI\termgraphData


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----      2021-09-01   오후 4:10             44 marketDominance.dat


    디렉터리: D:\CySECstudy\MyProgrammingProject\LiveCryptoPanel\LiveCLICryptoPanel_upbitAPI\__pycache__


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----      2021-08-30   오전 1:14           4810 LiveCryptoPanel_upbitAPI.cpython-38.pyc
```

Applied code
활용 코드
```py
        # Draw Market Dominance Graph
        termgraphDataMarketDominance = open("termgraphData/marketDominance.dat", 'w')
        termgraphDataMarketDominance.write("Market,{},{}".format(totalUPBITKRWMarketTradePrice24hr, totalUPBITBTCMarketTradePrice24hr))

        # Close saved file
        termgraphDataMarketDominance.close()




        exchangeTradingVolumeNotificationMessage = Back.CYAN + Fore.WHITE + Style.BRIGHT + "[UPBIT 최근 24시간 거래량] KRW마켓 ≈ ₩ {:,} | BTC마켓 ≈ ₩ {:,} | 합산 ≈ ₩ {:,}".format(
                    round(totalUPBITKRWMarketTradePrice24hr), round(totalUPBITBTCMarketTradePrice24hr),
                    round(totalUPBITKRWMarketTradePrice24hr + totalUPBITBTCMarketTradePrice24hr)) + Style.RESET_ALL

        os.system("""termgraph termgraphData/marketDominance.dat --color {{yellow,magenta}} --stacked --title "Stacked Data""")

        print(exchangeTradingVolumeNotificationMessage)
```
**Be careful when displaying the relative path. Also check if the extension is ".bat" rather than ".dat", and do not display the current directory in the relative path indication. For more information, see the upper code.**
**상대 경로 표시할 때 주의해야 한다. 또한 확장자를 ".dat"이 아닌 ".bat"으로 했는지도 확인해보고, 상대경로 표시에 있어 현재 Directory 는 표시하지 않아야 한다. 자세한 내용은 위 코드 참고.**

dat파일 내용
contents of dat file
```
Market,11764240790283.424,414041779002.01904
```

Python understands brackets as special characters, so you have to write them twice to indicate themselves.
파이썬에서는 중괄호를 특수한 문자로 이해하므로 중괄호 자체를 표기하기 위해서는 두 번 써 주어야 한다.

Instead, it would be nice to actively apply to other versions of the program that use the same API.
대신, 같은 API를 사용하는 다른 버전의 프로그램에 적극 적용하면 좋을 것 같다.

If this function is actively used in other versions, it is expected to implement functions such as market capitalization, comparison of BTC market transaction volume with KRW market, and drawing market graphs with specific cryptocurrencies.
다른 버전에서 이 기능을 적극적으로 사용만 한다면 시가총액, KRW 마켓과 BTC 마켓 거래량 비교, 특정 암호화폐로 시세 그래프를 그린다는 등의 기능을 구현할 것으로 기대된다.

**Comment by KnightChaser** [comment]
**_Once all changes that had been worked on the main were cancelled and turned back.
일단 main에서 작업한 모든 변경사항은 취소하고 뒤로 되돌렸다._**

There is no change, but this will be useful for creating another version of the program using the Upbit API in the future.
변경된 사항은 없지만 이번 내용은 향후 추가로 Upbit API를 활용하여 다른 버전의 프로그램을 만들때 유용하게 쓰일 것 같다.

**Comment by KnightChaser** [comment]
[https://pypi.org/project/plotext/](https://pypi.org/project/plotext/)

I found a package called Plotext, which offers a variety of features, is more intuitive, and is **not a command-based execution**! Why don't you try it?
다양한 기능을 제공하고 보다 더 직관적이며, **명령어 기반 실행방식이 아닌** plotext란 패키지를 찾았다! 한번 사용해보는건 어떨까?
