### ISSUE TITLE
[LiveCryptoPanel_upbitAPI] Runtime error : ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by KnightChaser** [x3onkait/LiveCLICryptoPanel#17]
Countered unexpected runtime error.
예상치 못한 런타임 오류에 맞닥뜨렸다.

As a bug, it is better to find the cause and solve it.
버그인만큼, 원인을 찾아 해결하는 것이 좋겠다.

It is not so bad(**critical**) to classify it as Critical because it is a sudden occurrence in the 927th update, but it is estimated that the Internet was cut once in the middle, and this error seems to have occurred when the data was not properly received.
흔히 발생하는 오류라고 하기에는 잘 작동하다가 927번째 업데이트에서 갑자기 발생한 것이라서 Critical로 분류하기는 정도가 심하지 않고, 또 추정하건데 중간에 인터넷이 한번 끊어졌는데 이때 데이터가 제대로 받아와지지 못하면서 이런 오류가 발생한 것으로 보인다.

```
Traceback (most recent call last):
  File ".\LiveCryptoPanel_upbitAPI.py", line 287, in <module>
    runProgram()
  File ".\LiveCryptoPanel_upbitAPI.py", line 240, in runProgram
    FLAG, cryptoDataBundle, totalUPBITKRWMarketTradePrice24hr, totalUPBITBTCMarketTradePrice24hr, currentBTCprice = cryptoDataProcessing(cryptoDataBundle, dataSortCriterion, sortDirection)
ValueError: too many values to unpack (expected 5)
```

**Comment by KnightChaser** [comment]
It seems too much to make exception handlings to the Internet being cut off, and it seems that there is no need to go into too much detail because it is a simple project here.
인터넷이 끊어진 것까지 예외처리를 하기에는 너무 과도한 것 같다. 일단 여기서는 간단한 프로젝트이므로 너무 자세하게 들어갈 필요는 없는 것 같다.

**Instead, it seems necessary to improve the current error processing system, which is somewhat ambiguous and too comprehensive, such as processing error processing as one of the Expedition statements. This is difficult to manage when the program grows, so it seems that the work should be executed first.
대신 에러 처리를 Exception 문 하나로 처리하는 등 다소 애매하고 너무 포괄적으로 표현한 현재의 에러 처리 체계를 조금 더 개선할 필요가 있을 것 같다. 이는 프로그램이 커지면 관리하기 어려우므로 우선적으로 작업을 실행해야 할 것 같다.**

**Comment by KnightChaser** [comment]
Anyway, I'll close this issue, and if similar errors occur after future improvements, this issue should be reopened.
일단 이 Issue는 닫고, 향후 개선 후에도 비슷한 에러가 발생하면 이 Issue를 Reopen해야겠다.

**Comment by KnightChaser** [comment]
Even if the Internet connection is good, it has been confirmed that this problem continues to occur several times during the program execution.
인터넷 연결이 잘 되어도 프로그램 실행 도중 계속 이 문제가 몇 번 발생하는 것이 확인되었다.

**Bug fix is needed!
버그 수정 필요!**

**Comment by KnightChaser** [comment]
The try-catch statement was used to allow the program to run again without turning off in the event of an error.
try-catch 문을 사용하여 에러 발생시 프로그램이 꺼지지 않고 재실행되도록 손을 봐 두었다.

If the future time allows, we can run the program for more than 5,000 update cycles to see if errors occur.
향후 시간이 허락한다면 5,000 업데이트 주기 이상의 시간동안 프로그램을 실행하여 오류가 발생하는지 확인하면 될 듯 하다.
